In [ ]:
import pandas as pd

artist_terms_embedding = pd.read_pickle('/content/drive/MyDrive/MSD/artist_terms_embeddings_matrix.pkl')
cofiltering_embeddings = pd.read_pickle('/content/drive/MyDrive/MSD/cofiltering_embeddings_matrix.pkl')
meta_data = pd.read_csv('/content/drive/MyDrive/MSD/tt_meta_joined.csv')

In [ ]:
#artist_terms_embedding.head()
#cofiltering_embeddings.head()
meta_data.drop(meta_data.iloc[:,2:1002],inplace=True,axis=1)

In [ ]:
artist_terms_embedding = artist_terms_embedding.rename(columns={'embeddings':'artist_terms_embeddings'})
artist_terms_embedding

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,song_id
0,0.000000,0.0,0.000000,0.040452,0.027059,0.021359,0.000000,0.000000,0.000000,0.000000,...,0.0,0.041485,0.007465,0.024736,0.008512,0.085083,0.000000,0.0,0.000000,b'SOCRUBZ12A58A7A6C3'
1,0.000000,0.0,0.000000,0.038536,0.046519,0.017784,0.001106,0.010277,0.000000,0.023664,...,0.0,0.000000,0.018367,0.000000,0.042299,0.064378,0.000000,0.0,0.013630,b'SOCHAXM12AB01876F8'
2,0.000000,0.0,0.012657,0.003815,0.036295,0.018004,0.000000,0.002241,0.000000,0.000000,...,0.0,0.000000,0.014075,0.000000,0.033059,0.058198,0.000000,0.0,0.005093,b'SOYLFWQ12A8C13DFF4'
3,0.000000,0.0,0.000000,0.042205,0.034748,0.041169,0.000000,0.027114,0.004479,0.000000,...,0.0,0.000614,0.021416,0.015196,0.044021,0.071036,0.018138,0.0,0.033959,b'SOVXNQF12A8C13075E'
4,0.000000,0.0,0.000000,0.018691,0.028751,0.030772,0.000000,0.000000,0.000000,0.009241,...,0.0,0.018830,0.000000,0.002687,0.008657,0.044531,0.000000,0.0,0.000000,b'SOTICDK12A8C13A367'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10000,0.017450,0.0,0.000000,0.073667,0.037432,0.045277,0.000000,0.013388,0.000000,0.001541,...,0.0,0.010052,0.034527,0.005630,0.048541,0.073453,0.000000,0.0,0.057149,b'SOEWCSS12A8C13AFFF'
10001,0.010369,0.0,0.018740,0.010007,0.044500,0.004447,0.000000,0.017478,0.002019,0.027218,...,0.0,0.000000,0.000000,0.000000,0.038698,0.045854,0.000000,0.0,0.000000,b'SOMCIPW12A8C144CA3'
10002,0.000000,0.0,0.000000,0.058840,0.000000,0.047422,0.000000,0.000000,0.000000,0.000000,...,0.0,0.008690,0.000000,0.000000,0.047338,0.054860,0.000000,0.0,0.022292,b'SOMONOL12AB01804C6'
10003,0.006615,0.0,0.000000,0.040255,0.020386,0.016332,0.000000,0.000000,0.000000,0.000000,...,0.0,0.016202,0.000000,0.023454,0.022919,0.057944,0.000000,0.0,0.004363,b'SOEJQOM12A8C13D882'
10004,0.000000,0.0,0.000000,0.008798,0.014601,0.014165,0.000000,0.002969,0.000000,0.000000,...,0.0,0.031549,0.016190,0.000000,0.001800,0.044707,0.000000,0.0,0.000604,b'SORBRJO12A8C13F0BC'

In [ ]:
cofiltering_embeddings = cofiltering_embeddings.rename(columns={'embeddings':'cofiltering_embeddings'})
cofiltering_embeddings

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,song_id
0,0.071865,0.146462,0.099309,0.0,0.0,0.0,0.0,0.0,0.0,0.017510,...,0.062182,0.157464,0.039663,0.166099,0.0,0.136595,0.157604,0.0,0.258377,b'SOCRUBZ12A58A7A6C3'
1,0.000000,0.000000,0.056479,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.002915,0.100579,0.022586,0.0,0.187963,0.221871,0.0,0.273653,b'SOCHAXM12AB01876F8'
2,0.000000,0.120326,0.083073,0.0,0.0,0.0,0.0,0.0,0.0,0.028034,...,0.000000,0.090546,0.011633,0.309717,0.0,0.237197,0.211936,0.0,0.268567,b'SOYLFWQ12A8C13DFF4'
3,0.004771,0.000000,0.135602,0.0,0.0,0.0,0.0,0.0,0.0,0.053340,...,0.000000,0.175342,0.108057,0.185343,0.0,0.209194,0.247692,0.0,0.213322,b'SOVXNQF12A8C13075E'
4,0.000000,0.089966,0.042336,0.0,0.0,0.0,0.0,0.0,0.0,0.107978,...,0.000000,0.109960,0.141078,0.187198,0.0,0.282225,0.159585,0.0,0.284263,b'SOTICDK12A8C13A367'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.018078,0.000303,0.087436,0.0,0.0,0.0,0.0,0.0,0.0,0.063134,...,0.000000,0.152046,0.054177,0.186511,0.0,0.135987,0.190105,0.0,0.272392,b'SOEWCSS12A8C13AFFF'
9996,0.023799,0.000000,0.154472,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.030065,0.046729,0.185681,0.0,0.232341,0.165357,0.0,0.228144,b'SOMCIPW12A8C144CA3'
9997,0.021132,0.000000,0.132676,0.0,0.0,0.0,0.0,0.0,0.0,0.044222,...,0.000000,0.144242,0.000000,0.091493,0.0,0.179120,0.175604,0.0,0.263317,b'SOMONOL12AB01804C6'
9998,0.022062,0.017326,0.058560,0.0,0.0,0.0,0.0,0.0,0.0,0.031393,...,0.000000,0.000000,0.156604,0.176791,0.0,0.117625,0.203728,0.0,0.172650,b'SOEJQOM12A8C13D882'
9999,0.000000,0.046915,0.187862,0.0,0.0,0.0,0.0,0.0,0.0,0.059647,...,0.000000,0.038937,0.066810,0.173742,0.0,0.159091,0.166275,0.0,0.242276,b'SORBRJO12A8C13F0BC'

In [ ]:
meta_data.columns

Index(['Unnamed: 0', 'song_id', 'f_name', 'artist_hotttnesss', 'artist_id',
       'artist_name', 'release', 'release_7digitalid', 'similar_artists',
       'song_hotttnesss', 'title', 'track_7digitalid', 'audio_md5',
       'danceability', 'duration', 'energy', 'key', 'key_confidence',
       'loudness', 'mode', 'mode_confidence', 'tempo', 'time_signature',
       'time_signature_confidence', 'track_id', 'year', 'artist_terms',
       'artist_terms_weight'],
      dtype='object')

In [ ]:
meta_data.drop(meta_data.columns[[0,2,4,5,6,7,8,10,11,12,13,15,24,25,26,27]],inplace=True,axis=1)

In [ ]:
meta_data

,song_id,artist_hotttnesss,song_hotttnesss,duration,key,key_confidence,loudness,mode,mode_confidence,tempo,time_signature,time_signature_confidence
0,b'SOCRUBZ12A58A7A6C3',0.455616,NaN,293.72036,9,0.235,-7.378,1,0.541,211.939,4,0.473
1,b'SOCHAXM12AB01876F8',0.376279,0.428734,249.07710,11,0.294,-6.297,1,0.450,116.035,5,0.538
2,b'SOYLFWQ12A8C13DFF4',0.330190,NaN,238.73261,11,0.021,-7.699,0,0.404,94.995,5,0.878
3,b'SOVXNQF12A8C13075E',0.468797,0.407233,195.89179,9,0.587,-9.365,0,0.432,166.237,4,0.000
4,b'SOTICDK12A8C13A367',0.353321,0.000000,379.24526,0,0.860,-6.041,1,0.688,172.948,4,0.047
...,...,...,...,...,...,...,...,...,...,...,...,...
10000,b'SOEWCSS12A8C13AFFF',0.390589,0.417081,295.99302,8,0.170,-9.422,1,0.365,114.894,4,0.546
10001,b'SOMCIPW12A8C144CA3',0.388439,0.484563,171.70240,10,0.516,-8.540,0,0.377,112.950,4,0.000
10002,b'SOMONOL12AB01804C6',0.430623,NaN,291.39546,11,0.151,-21.139,0,0.354,151.705,3,0.724
10003,b'SOEJQOM12A8C13D882',0.587479,0.842704,291.00363,7,0.529,-6.178,0,0.610,117.384,4,1.000
10004,b'SORBRJO12A8C13F0BC',0.534166,NaN,255.16363,2,0.628,-9.075,1,0.632,79.931,4,0.737

In [ ]:
from functools import reduce

dataframes = [cofiltering_embeddings,artist_terms_embedding,meta_data]

In [ ]:
dataset = reduce(lambda left,right: pd.merge(left,right,on=['song_id'], how='inner'),dataframes)

In [ ]:
song_counts = pd.read_pickle('/content/drive/MyDrive/MSD/user_song_counts.pkl')
dataset['listen_count'] = song_counts['325e8fcea8e1f6c8595edb169a245b12c2f5fd2b']
dataset
#meta_data['listen_count'] = song_counts['325e8fcea8e1f6c8595edb169a245b12c2f5fd2b']

,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,...,duration,key,key_confidence,loudness,mode,mode_confidence,tempo,time_signature,time_signature_confidence,listen_count
0,0.071865,0.146462,0.099309,0.0,0.0,0.0,0.0,0.0,0.0,0.017510,...,293.72036,9,0.235,-7.378,1,0.541,211.939,4,0.473,95.0
1,0.000000,0.000000,0.056479,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,249.07710,11,0.294,-6.297,1,0.450,116.035,5,0.538,10.0
2,0.000000,0.120326,0.083073,0.0,0.0,0.0,0.0,0.0,0.0,0.028034,...,238.73261,11,0.021,-7.699,0,0.404,94.995,5,0.878,12.0
3,0.004771,0.000000,0.135602,0.0,0.0,0.0,0.0,0.0,0.0,0.053340,...,195.89179,9,0.587,-9.365,0,0.432,166.237,4,0.000,32.0
4,0.000000,0.089966,0.042336,0.0,0.0,0.0,0.0,0.0,0.0,0.107978,...,379.24526,0,0.860,-6.041,1,0.688,172.948,4,0.047,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10010,0.018078,0.000303,0.087436,0.0,0.0,0.0,0.0,0.0,0.0,0.063134,...,295.99302,8,0.170,-9.422,1,0.365,114.894,4,0.546,NaN
10011,0.023799,0.000000,0.154472,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,171.70240,10,0.516,-8.540,0,0.377,112.950,4,0.000,NaN
10012,0.021132,0.000000,0.132676,0.0,0.0,0.0,0.0,0.0,0.0,0.044222,...,291.39546,11,0.151,-21.139,0,0.354,151.705,3,0.724,NaN
10013,0.022062,0.017326,0.058560,0.0,0.0,0.0,0.0,0.0,0.0,0.031393,...,291.00363,7,0.529,-6.178,0,0.610,117.384,4,1.000,NaN
10014,0.000000,0.046915,0.187862,0.0,0.0,0.0,0.0,0.0,0.0,0.059647,...,255.16363,2,0.628,-9.075,1,0.632,79.931,4,0.737,NaN

In [ ]:
dataset = dataset[dataset['listen_count'].notna()]
dataset=dataset.fillna(0)
dataset['tempo']=dataset['tempo']/dataset['tempo'].abs().max()
dataset

,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,...,duration,key,key_confidence,loudness,mode,mode_confidence,tempo,time_signature,time_signature_confidence,listen_count
0,0.071865,0.146462,0.099309,0.0,0.0,0.0,0.0,0.000000,0.0,0.017510,...,293.72036,9,0.235,-7.378,1,0.541,0.818357,4,0.473,95.0
1,0.000000,0.000000,0.056479,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,249.07710,11,0.294,-6.297,1,0.450,0.448044,5,0.538,10.0
2,0.000000,0.120326,0.083073,0.0,0.0,0.0,0.0,0.000000,0.0,0.028034,...,238.73261,11,0.021,-7.699,0,0.404,0.366803,5,0.878,12.0
3,0.004771,0.000000,0.135602,0.0,0.0,0.0,0.0,0.000000,0.0,0.053340,...,195.89179,9,0.587,-9.365,0,0.432,0.641889,4,0.000,32.0
4,0.000000,0.089966,0.042336,0.0,0.0,0.0,0.0,0.000000,0.0,0.107978,...,379.24526,0,0.860,-6.041,1,0.688,0.667802,4,0.047,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.060209,0.080937,0.107248,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,171.36281,4,0.657,-9.164,1,0.626,0.400172,3,1.000,90.0
9996,0.124158,0.098313,0.080376,0.0,0.0,0.0,0.0,0.000000,0.0,0.007732,...,220.76036,7,0.127,-12.670,1,0.408,0.626085,4,0.797,9.0
9997,0.000000,0.072793,0.077195,0.0,0.0,0.0,0.0,0.016568,0.0,0.051529,...,237.26975,8,0.669,-7.388,1,0.457,0.756828,3,1.000,52.0
9998,0.000000,0.120404,0.035290,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,222.24934,1,0.347,-8.648,1,0.570,0.392770,3,0.616,49.0
9999,0.014545,0.076467,0.020645,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,179.66975,8,0.336,-9.178,1,0.416,0.294056,1,0.873,10.0

In [ ]:
'''
meta_data = meta_data[meta_data['listen_count'].notna()]
meta_data=meta_data.fillna(0)
meta_data['tempo']=meta_data['tempo']/meta_data['tempo'].abs().max()
meta_data
meta_data.isnull().values.any()
'''
dataset.isnull().values.any()

False

In [ ]:
input_data = dataset.copy()
input_data.drop(columns=['song_id'],inplace=True)
input_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 0 to 9999
Data columns (total 76 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   0_x                        10000 non-null  float32
 1   1_x                        10000 non-null  float32
 2   2_x                        10000 non-null  float32
 3   3_x                        10000 non-null  float32
 4   4_x                        10000 non-null  float32
 5   5_x                        10000 non-null  float32
 6   6_x                        10000 non-null  float32
 7   7_x                        10000 non-null  float32
 8   8_x                        10000 non-null  float32
 9   9_x                        10000 non-null  float32
 10  10_x                       10000 non-null  float32
 11  11_x                       10000 non-null  float32
 12  12_x                       10000 non-null  float32
 13  13_x                       10000 non-null  float32
 14  14_x                       10000 non-null  float32
 15  15_x                       10000 non-null  float32
 16  16_x                       10000 non-null  float32
 17  17_x                       10000 non-null  float32
 18  18_x                       10000 non-null  float32
 19  19_x                       10000 non-null  float32
 20  20_x                       10000 non-null  float32
 21  21_x                       10000 non-null  float32
 22  22_x                       10000 non-null  float32
 23  23_x                       10000 non-null  float32
 24  24_x                       10000 non-null  float32
 25  25_x                       10000 non-null  float32
 26  26_x                       10000 non-null  float32
 27  27_x                       10000 non-null  float32
 28  28_x                       10000 non-null  float32
 29  29_x                       10000 non-null  float32
 30  30_x                       10000 non-null  float32
 31  31_x                       10000 non-null  float32
 32  0_y                        10000 non-null  float32
 33  1_y                        10000 non-null  float32
 34  2_y                        10000 non-null  float32
 35  3_y                        10000 non-null  float32
 36  4_y                        10000 non-null  float32
 37  5_y                        10000 non-null  float32
 38  6_y                        10000 non-null  float32
 39  7_y                        10000 non-null  float32
 40  8_y                        10000 non-null  float32
 41  9_y                        10000 non-null  float32
 42  10_y                       10000 non-null  float32
 43  11_y                       10000 non-null  float32
 44  12_y                       10000 non-null  float32
 45  13_y                       10000 non-null  float32
 46  14_y                       10000 non-null  float32
 47  15_y                       10000 non-null  float32
 48  16_y                       10000 non-null  float32
 49  17_y                       10000 non-null  float32
 50  18_y                       10000 non-null  float32
 51  19_y                       10000 non-null  float32
 52  20_y                       10000 non-null  float32
 53  21_y                       10000 non-null  float32
 54  22_y                       10000 non-null  float32
 55  23_y                       10000 non-null  float32
 56  24_y                       10000 non-null  float32
 57  25_y                       10000 non-null  float32
 58  26_y                       10000 non-null  float32
 59  27_y                       10000 non-null  float32
 60  28_y                       10000 non-null  float32
 61  29_y                       10000 non-null  float32
 62  30_y                       10000 non-null  float32
 63  31_y                       10000 non-null  float32
 64  artist_hotttnesss          10000 non-null  float64
 65  song_hotttnesss            10000 non-null  float64
 66  duration                   10000 non-null  float64
 67  key                        10000 non-null  int64
 68  key_confidence             10000 non-null  float64
 69  loudness                   10000 non-null  float64
 70  mode                       10000 non-null  int64
 71  mode_confidence            10000 non-null  float64
 72  tempo                      10000 non-null  float64
 73  time_signature             10000 non-null  int64
 74  time_signature_confidence  10000 non-null  float64
 75  listen_count               10000 non-null  float64
dtypes: float32(64), float64(9), int64(3)
memory usage: 3.4 MB

In [ ]:
input_data = input_data.to_numpy()
input_data = np.asarray(input_data).astype('float32')
input_data.shape

(10000, 76)

In [ ]:
print(type(input_data[0][0]))

<class 'tuple'>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import pprint
from tensorflow.keras.utils import to_categorical
from scipy.spatial.distance import cdist
from sklearn.metrics import davies_bouldin_score, silhouette_score
import pickle
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf 
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import SGD, Adam
from keras import layers
import keras
import datetime, os
import matplotlib.pyplot as plt
from sklearn.metrics import davies_bouldin_score, silhouette_score
from sklearn.cluster import KMeans

In [ ]:
#Autoencoder architecture 

model = Sequential()
'''
model.add(Dense(500, input_dim=75, activation= "relu"))
model.add(Dense(100, activation= "relu"))
model.add(Dense(50, activation= "relu"))
model.add(Dense(1))

'''
input_shape = keras.Input(shape=(43, ))

#Encoder
#e = layers.Dense(1024, activation='relu')(input_shape)

#e = layers.Dense(512, activation='relu')(input_shape)

e = layers.Dense(256, activation='relu')(e)
e = layers.Dropout(0.5)(e)
e = layers.Dense(128, activation='relu')(e)
e = layers.Dropout(0.5)(e)
e = layers.Dense(64, activation='relu')(e)
e = layers.Dropout(0.5)(e)
e = layers.Dense(32, activation='relu')(e)
e = layers.Dropout(0.5)(e)
e = layers.Dense(16, activation='relu')(e)
e = layers.Dense(1, activation='linear',name = 'listen_count')(e)
#e = layers.MaxPooling2D((2, 2), padding='same', name = 'encoded')(e)

'''
d = layers.Dense(64, activation='relu')(e)
d = layers.Dropout(0.5)(d)
#d = layers.UpSampling2D((2, 2))(d)
d = layers.Dense(128, activation='relu')(d)
d = layers.Dropout(0.5)(d)
#d = layers.UpSampling2D((2, 2))(d)
d = layers.Dense(256, activation='relu')(d)
d = layers.Dropout(0.5)(d)
#d = layers.UpSampling2D((2, 2))(d)
d = layers.Dense(512, activation='relu')(d)
d = layers.Dropout(0.5)(d)
d = layers.Dense(786, activation='relu')(d)
d = layers.Dense(6730, activation='relu')(d)




autoencoder = keras.Model(input_shape, d)
autoencoder.compile(optimizer='adam', loss=tf.keras.losses.MeanSquaredError())
print(autoencoder.summary())

#Extracting latent variables
layer_name = 'encoded'
intermediate_layer_model = keras.Model(inputs = autoencoder.input, outputs=autoencoder.get_layer(layer_name).output)
intermediate_output = intermediate_layer_model(x_train)
'''
recommender = keras.Model(input_shape, e)
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
recommender.compile(optimizer=opt, loss=tf.keras.losses.MeanSquaredError())
print(recommender.summary())

layer_name = 'listen_count'
intermediate_layer_model = keras.Model(inputs = recommender.input, outputs=recommender.get_layer(layer_name).output)
intermediate_output = intermediate_layer_model(input_features_train)

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_3 (InputLayer)        [(None, 43)]              0

 dense_12 (Dense)            (None, 512)               22528

 dense_13 (Dense)            (None, 256)               131328

 dropout_8 (Dropout)         (None, 256)               0

 dense_14 (Dense)            (None, 128)               32896

 dropout_9 (Dropout)         (None, 128)               0

 dense_15 (Dense)            (None, 64)                8256

 dropout_10 (Dropout)        (None, 64)                0

 dense_16 (Dense)            (None, 32)                2080

 dropout_11 (Dropout)        (None, 32)                0

 dense_17 (Dense)            (None, 16)                528

 listen_count (Dense)        (None, 1)                 17

=================================================================
Total params: 197,633
Trainable params: 197,633
Non-trainable params: 0
_________________________________________________________________
None

In [ ]:
input_features_train = input_data[:8000,32:75]
input_features_test = input_data[8000:,32:75]
output_train = input_data[:8000,75:]
output_test = input_data[8000:,75:]

In [ ]:
recommender.fit(input_features_train,output_train,
                epochs=100,
                batch_size=128,
                shuffle=True,
                validation_data=(input_features_test,output_test ))

Epoch 1/100
63/63 [==============================] - 0s 5ms/step - loss: 824.9399 - val_loss: 863.2219
Epoch 2/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9415 - val_loss: 863.7789
Epoch 3/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5883 - val_loss: 864.4283
Epoch 4/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2454 - val_loss: 863.0168
Epoch 5/100
63/63 [==============================] - 0s 5ms/step - loss: 825.7727 - val_loss: 862.9979
Epoch 6/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9874 - val_loss: 863.0446
Epoch 7/100
63/63 [==============================] - 0s 5ms/step - loss: 825.7546 - val_loss: 862.9974
Epoch 8/100
63/63 [==============================] - 0s 5ms/step - loss: 824.8973 - val_loss: 863.4507
Epoch 9/100
63/63 [==============================] - 0s 6ms/step - loss: 825.0103 - val_loss: 867.3037
Epoch 10/100
63/63 [==============================] - 0s 5ms/step - loss: 826.4304 - val_loss: 863.5400
Epoch 11/100
63/63 [==============================] - 0s 5ms/step - loss: 825.1381 - val_loss: 863.1510
Epoch 12/100
63/63 [==============================] - 0s 5ms/step - loss: 825.6583 - val_loss: 863.2015
Epoch 13/100
63/63 [==============================] - 0s 5ms/step - loss: 826.4457 - val_loss: 863.3076
Epoch 14/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5629 - val_loss: 863.0920
Epoch 15/100
63/63 [==============================] - 0s 5ms/step - loss: 825.4124 - val_loss: 863.0833
Epoch 16/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9371 - val_loss: 863.7258
Epoch 17/100
63/63 [==============================] - 0s 5ms/step - loss: 825.6998 - val_loss: 863.0038
Epoch 18/100
63/63 [==============================] - 0s 5ms/step - loss: 825.0286 - val_loss: 864.6451
Epoch 19/100
63/63 [==============================] - 0s 5ms/step - loss: 825.4225 - val_loss: 863.0218
Epoch 20/100
63/63 [==============================] - 0s 5ms/step - loss: 825.7198 - val_loss: 863.4115
Epoch 21/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2292 - val_loss: 863.0157
Epoch 22/100
63/63 [==============================] - 0s 5ms/step - loss: 825.1548 - val_loss: 863.1501
Epoch 23/100
63/63 [==============================] - 0s 5ms/step - loss: 825.7012 - val_loss: 865.1378
Epoch 24/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2729 - val_loss: 863.1366
Epoch 25/100
63/63 [==============================] - 0s 5ms/step - loss: 826.3476 - val_loss: 863.6889
Epoch 26/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2261 - val_loss: 863.0564
Epoch 27/100
63/63 [==============================] - 0s 5ms/step - loss: 824.7182 - val_loss: 865.2784
Epoch 28/100
63/63 [==============================] - 0s 5ms/step - loss: 826.7991 - val_loss: 863.2589
Epoch 29/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5064 - val_loss: 865.9966
Epoch 30/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9568 - val_loss: 864.4796
Epoch 31/100
63/63 [==============================] - 0s 5ms/step - loss: 825.6068 - val_loss: 863.3103
Epoch 32/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5245 - val_loss: 863.0086
Epoch 33/100
63/63 [==============================] - 0s 5ms/step - loss: 825.1456 - val_loss: 863.2358
Epoch 34/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2921 - val_loss: 864.4291
Epoch 35/100
63/63 [==============================] - 0s 5ms/step - loss: 825.0717 - val_loss: 863.0752
Epoch 36/100
63/63 [==============================] - 0s 5ms/step - loss: 824.7787 - val_loss: 865.5640
Epoch 37/100
63/63 [==============================] - 0s 5ms/step - loss: 826.3807 - val_loss: 863.7607
Epoch 38/100
63/63 [==============================] - 0s 5ms/step - loss: 825.4836 - val_loss: 864.1300
Epoch 39/100
63/63 [==============================] - 0s 5ms/step - loss: 825.3749 - val_loss: 863.0648
Epoch 40/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5805 - val_loss: 865.1492
Epoch 41/100
63/63 [==============================] - 0s 5ms/step - loss: 824.7479 - val_loss: 863.0887
Epoch 42/100
63/63 [==============================] - 0s 5ms/step - loss: 826.0068 - val_loss: 863.1578
Epoch 43/100
63/63 [==============================] - 0s 5ms/step - loss: 825.4325 - val_loss: 863.2124
Epoch 44/100
63/63 [==============================] - 0s 5ms/step - loss: 824.9525 - val_loss: 863.6428
Epoch 45/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9999 - val_loss: 864.9117
Epoch 46/100
63/63 [==============================] - 0s 5ms/step - loss: 826.1079 - val_loss: 863.9656
Epoch 47/100
63/63 [==============================] - 0s 5ms/step - loss: 826.5148 - val_loss: 864.5920
Epoch 48/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9394 - val_loss: 863.0009
Epoch 49/100
63/63 [==============================] - 0s 5ms/step - loss: 825.4092 - val_loss: 863.6193
Epoch 50/100
63/63 [==============================] - 0s 5ms/step - loss: 826.7241 - val_loss: 864.5480
Epoch 51/100
63/63 [==============================] - 0s 5ms/step - loss: 826.0270 - val_loss: 863.0999
Epoch 52/100
63/63 [==============================] - 0s 5ms/step - loss: 825.8806 - val_loss: 863.3669
Epoch 53/100
63/63 [==============================] - 0s 5ms/step - loss: 825.6070 - val_loss: 863.3665
Epoch 54/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2969 - val_loss: 863.0285
Epoch 55/100
63/63 [==============================] - 0s 5ms/step - loss: 825.4795 - val_loss: 863.0010
Epoch 56/100
63/63 [==============================] - 0s 5ms/step - loss: 825.7266 - val_loss: 863.0156
Epoch 57/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5267 - val_loss: 865.6190
Epoch 58/100
63/63 [==============================] - 0s 5ms/step - loss: 826.8077 - val_loss: 867.5351
Epoch 59/100
63/63 [==============================] - 0s 5ms/step - loss: 826.2745 - val_loss: 863.7411
Epoch 60/100
63/63 [==============================] - 0s 5ms/step - loss: 825.6283 - val_loss: 863.1835
Epoch 61/100
63/63 [==============================] - 0s 6ms/step - loss: 825.1318 - val_loss: 863.4346
Epoch 62/100
63/63 [==============================] - 0s 5ms/step - loss: 825.6168 - val_loss: 863.5344
Epoch 63/100
63/63 [==============================] - 0s 5ms/step - loss: 825.3852 - val_loss: 863.5471
Epoch 64/100
63/63 [==============================] - 0s 5ms/step - loss: 825.8648 - val_loss: 863.2165
Epoch 65/100
63/63 [==============================] - 0s 5ms/step - loss: 825.3117 - val_loss: 863.2207
Epoch 66/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2953 - val_loss: 865.6019
Epoch 67/100
63/63 [==============================] - 0s 5ms/step - loss: 825.8886 - val_loss: 863.0297
Epoch 68/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9320 - val_loss: 864.0427
Epoch 69/100
63/63 [==============================] - 0s 5ms/step - loss: 826.3869 - val_loss: 862.9990
Epoch 70/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5809 - val_loss: 863.6041
Epoch 71/100
63/63 [==============================] - 0s 5ms/step - loss: 825.3978 - val_loss: 863.5339
Epoch 72/100
63/63 [==============================] - 0s 6ms/step - loss: 825.8154 - val_loss: 863.0051
Epoch 73/100
63/63 [==============================] - 0s 5ms/step - loss: 825.6339 - val_loss: 863.1771
Epoch 74/100
63/63 [==============================] - 0s 5ms/step - loss: 825.1710 - val_loss: 863.2344
Epoch 75/100
63/63 [==============================] - 0s 5ms/step - loss: 825.8555 - val_loss: 864.4949
Epoch 76/100
63/63 [==============================] - 0s 5ms/step - loss: 825.0516 - val_loss: 863.0608
Epoch 77/100
63/63 [==============================] - 0s 5ms/step - loss: 825.1850 - val_loss: 863.0271
Epoch 78/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2059 - val_loss: 863.9490
Epoch 79/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9598 - val_loss: 862.9993
Epoch 80/100
63/63 [==============================] - 0s 5ms/step - loss: 825.7902 - val_loss: 863.0506
Epoch 81/100
63/63 [==============================] - 0s 5ms/step - loss: 825.6390 - val_loss: 864.4654
Epoch 82/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2318 - val_loss: 863.3636
Epoch 83/100
63/63 [==============================] - 0s 5ms/step - loss: 824.9366 - val_loss: 865.2249
Epoch 84/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5499 - val_loss: 863.0005
Epoch 85/100
63/63 [==============================] - 0s 5ms/step - loss: 824.9246 - val_loss: 863.0405
Epoch 86/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5666 - val_loss: 863.1550
Epoch 87/100
63/63 [==============================] - 0s 5ms/step - loss: 825.3375 - val_loss: 863.3345
Epoch 88/100
63/63 [==============================] - 0s 5ms/step - loss: 825.3790 - val_loss: 862.9974
Epoch 89/100
63/63 [==============================] - 0s 5ms/step - loss: 825.5952 - val_loss: 863.3517
Epoch 90/100
63/63 [==============================] - 0s 5ms/step - loss: 825.4179 - val_loss: 863.3372
Epoch 91/100
63/63 [==============================] - 0s 5ms/step - loss: 825.0020 - val_loss: 867.6951
Epoch 92/100
63/63 [==============================] - 0s 5ms/step - loss: 825.7851 - val_loss: 873.5093
Epoch 93/100
63/63 [==============================] - 0s 5ms/step - loss: 827.6508 - val_loss: 865.7039
Epoch 94/100
63/63 [==============================] - 0s 5ms/step - loss: 825.4801 - val_loss: 865.4395
Epoch 95/100
63/63 [==============================] - 0s 6ms/step - loss: 826.4843 - val_loss: 866.5825
Epoch 96/100
63/63 [==============================] - 0s 5ms/step - loss: 825.2936 - val_loss: 863.0134
Epoch 97/100
63/63 [==============================] - 0s 5ms/step - loss: 826.0934 - val_loss: 863.9938
Epoch 98/100
63/63 [==============================] - 0s 5ms/step - loss: 825.9629 - val_loss: 863.2556
Epoch 99/100
63/63 [==============================] - 0s 5ms/step - loss: 826.5500 - val_loss: 864.1254
Epoch 100/100
63/63 [==============================] - 0s 5ms/step - loss: 826.2979 - val_loss: 864.5649

In [ ]:
linear_outputs = intermediate_output.numpy()

In [ ]:
print(linear_outputs[:10])

[[4.3658285]
 [3.646102 ]
 [3.4772577]
 [2.8265612]
 [5.8509216]
 [2.7078166]
 [2.3661335]
 [0.7228354]
 [1.7933252]
 [3.824215 ]]